spring:
  application:
    name: dub-provider

server:
  port: 9901
dubbo:
  scan:
    base-packages: com.origin
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://124.71.79.139:2182
  protocols:
    prot1:
      name: dubbo
      port: 30880
#    prot2:
#      name: http
#      port: 30882
#    prot3:
#      id: rest
#      name: rest
#      port: 30083
  config-center:
    timeout: 30000

#  dubbo://172.21.22.85:30880/com.origin.QueryProcess?anyhost=true&application=dub-provider&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.origin.QueryProcess&methods=doQuery&pid=30316&release=2.7.5&revision=timeOut&side=provider&timeout=3000&timestamp=1640746365256&version=timeOut
#  http://172.21.22.85:30882/com.origin.QueryProcess?anyhost=true&application=dub-provider&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.origin.QueryProcess&methods=doQuery&pid=30316&release=2.7.5&revision=timeOut&side=provider&timeout=3000&timestamp=1640746365845&version=timeOut
#  dubbo://172.21.22.85:30880/com.origin.QueryProcess?anyhost=true&application=dub-provider&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.origin.QueryProcess&methods=doQuery&pid=30316&release=2.7.5&revision=default&side=provider&timestamp=1640746366184&version=default
#  http://172.21.22.85:30882/com.origin.QueryProcess?anyhost=true&application=dub-provider&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.origin.QueryProcess&methods=doQuery&pid=30316&release=2.7.5&revision=default&side=provider&timestamp=1640746366232&version=default